### ISSUE TITLE
1.19.4 doesn't work 💀 

### ISSUE THREAD

**Issue by doggoboiwastaken** [Inferis/packing-boxes#3]
The mod didn't make any changes to the game. There are no items found in the game that are from packing boxes.

**Comment by Inferis** [comment]
Hm, weird. I tested it and it worked fine for me. 

I'll take a look. 

-- Tom

**Comment by doggoboiwastaken** [comment]
[Here's what is happening for me](https://youtu.be/baNUDvaN02M?si=9gpHoiQidmZSgJMb)

TLDR;
- Both fabric API and the mod are installed-- nothing else. The latest 1.19.4 fabric API + the 1.19.4 you just made.
- Opens fine, with no errors in the log.
- Items not found. I looked through the entire creative inventory, but the packing tape and cardboard box were not there.

**Comment by Inferis** [comment]
Can you try enabling cheats and type 

/give @s packing_boxes:packing_tape

?

**Comment by doggoboiwastaken** [comment]
That worked. I received the item, and it did what was expected. However, it's still not accessible in survival.

**Comment by Inferis** [comment]
Yeah, I'll take a look later!

**Comment by doggoboiwastaken** [comment]
Thank you <3

**Comment by Inferis** [comment]
Should be fixed!
